import { useState, useEffect } from "react";
import { API_BASE } from "@/config/api";
import { DashboardLayout } from "@/components/DashboardLayout";
import { Badge } from "@/components/ui/badge";
import { motion, AnimatePresence } from "framer-motion";
import { Sparkles, Target, Clock, Lightbulb, Play, Bookmark, Filter, CheckCircle2, Bot, Loader2, RefreshCw } from "lucide-react";
import { Button } from "@/components/ui/button";
import { toast } from "sonner";
import { FocusMode } from "@/components/FocusMode";

interface Task {
  id: string;
  title: string;
  description: string;
  priority: "high" | "medium" | "low";
  duration: string;
  category: string;
}

export default function StudentSuggestions() {
  const token = localStorage.getItem("token");
  const user = JSON.parse(localStorage.getItem("user") || "{}");
  const [activeFilter, setActiveFilter] = useState("All");
  const filters = ["All", "High Priority", "Study", "Skills"];
  const [savedTasks, setSavedTasks] = useState<string[]>([]);
  const [tasks, setTasks] = useState<Task[]>([]);
  const [loading, setLoading] = useState(true);
  const [focusTask, setFocusTask] = useState<Task | null>(null);

  const fetchSuggestions = async () => {
    setLoading(true);
    try {
      const res = await fetch(`${API_BASE}/api/ai/suggestions`, {
        headers: { Authorization: `Bearer ${token}` }
      });
      const data = await res.json();
      if (res.ok && data.data) {
        setTasks(data.data);
      } else {
        toast.error("Could not load AI suggestions");
      }
    } catch {
      toast.error("Network error — could not connect to AI");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => { fetchSuggestions(); }, []);

  const toggleSave = (id: string) => {
    setSavedTasks(prev => prev.includes(id) ? prev.filter(t => t !== id) : [...prev, id]);
  };

  const filtered = tasks.filter(t => {
    if (activeFilter === "All") return true;
    if (activeFilter === "High Priority") return t.priority === "high";
    return t.category?.toLowerCase().includes(activeFilter.toLowerCase());
  });

  return (
    <DashboardLayout role="student" title="AI Task Engine">
      {/* Banner */}
      <motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} className="glass-card p-6 mb-8 relative overflow-hidden flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div className="absolute top-0 right-0 w-64 h-64 bg-primary/10 rounded-full blur-[100px] -mr-20 -mt-20 pointer-events-none" />
        <div className="z-10 relative">
          <h2 className="font-display font-semibold text-lg flex items-center gap-2 mb-2">
            <Lightbulb className="h-5 w-5 text-warning" />
            AI Suggestions for {user.name || "You"}
          </h2>
          <p className="text-muted-foreground text-sm max-w-xl">
            Personalized tasks generated by <strong>Groq llama-3.3-70b</strong> based on your timetable and attendance data.
          </p>
        </div>
        <div className="z-10 flex items-center gap-3">
          <div className="flex items-center gap-2 p-3 rounded-xl bg-primary/10 border border-primary/20">
            <Bot className="h-4 w-4 text-primary shrink-0" />
            <span className="text-xs text-primary font-medium">Groq AI · Live</span>
          </div>
          <Button variant="outline" size="sm" onClick={fetchSuggestions} disabled={loading} className="gap-2 border-white/20">
            <RefreshCw className={`w-4 h-4 ${loading ? "animate-spin" : ""}`} />
            Refresh
          </Button>
        </div>
      </motion.div>

      {/* Filters */}
      <div className="flex items-center gap-2 overflow-x-auto pb-2 scrollbar-none mb-6">
        <Button variant="ghost" size="sm" className="hidden text-muted-foreground mr-2 cursor-default pointer-events-none md:flex">
          <Filter className="w-4 h-4 mr-2" /> Filters
        </Button>
        {filters.map(f => (
          <Button
            key={f}
            variant={activeFilter === f ? "default" : "outline"}
            size="sm"
            onClick={() => setActiveFilter(f)}
            className={activeFilter === f ? "bg-primary text-primary-foreground" : "border-white/10 hover:bg-white/5"}
          >
            {f}
          </Button>
        ))}
      </div>

      {/* Cards */}
      {loading ? (
        <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-6">
          {[1, 2, 3, 4].map(i => (
            <div key={i} className="glass-card p-6 animate-pulse">
              <div className="w-8 h-8 bg-white/10 rounded-lg mb-4" />
              <div className="h-4 bg-white/10 rounded mb-2 w-3/4" />
              <div className="h-3 bg-white/10 rounded mb-1 w-full" />
              <div className="h-3 bg-white/10 rounded mb-4 w-2/3" />
              <div className="h-8 bg-white/10 rounded" />
            </div>
          ))}
        </div>
      ) : filtered.length === 0 ? (
        <div className="glass-card p-16 text-center text-muted-foreground opacity-50">
          <Bot className="w-12 h-12 mx-auto mb-3 opacity-30" />
          <p className="text-sm">No tasks match this filter.</p>
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-6">
          <AnimatePresence>
            {filtered.map((task, idx) => (
              <motion.div
                layout
                key={task.id}
                initial={{ opacity: 0, scale: 0.95 }}
                animate={{ opacity: 1, scale: 1 }}
                exit={{ opacity: 0, scale: 0.95 }}
                transition={{ delay: idx * 0.05 }}
                className="glass-card border border-white/5 hover:border-primary/30 p-0 flex flex-col group overflow-hidden bg-card/40 hover:bg-card/60 transition-colors"
              >
                <div className="p-6 flex flex-col flex-1">
                  <div className="flex items-start justify-between mb-3">
                    <div className="w-8 h-8 rounded-lg bg-primary/20 flex items-center justify-center">
                      <Sparkles className="h-4 w-4 text-primary" />
                    </div>
                    <Badge
                      variant="secondary"
                      className={`text-[10px] uppercase font-bold tracking-wider ${
                        task.priority === "high" ? "bg-destructive/10 text-destructive" :
                        task.priority === "medium" ? "bg-warning/10 text-warning" :
                        "bg-muted text-muted-foreground"
                      }`}
                    >
                      {task.priority} Priority
                    </Badge>
                  </div>

                  <h3 className="font-semibold text-lg mb-2">{task.title}</h3>
                  <p className="text-sm text-muted-foreground line-clamp-3 mb-4 flex-1">{task.description}</p>

                  <div className="flex items-center gap-4 text-xs font-medium text-foreground/70 mb-6 bg-white/5 p-3 rounded-lg">
                    <span className="flex items-center gap-1.5"><Clock className="h-3.5 w-3.5 text-primary" /> {task.duration}</span>
                    <div className="w-px h-3 bg-white/10" />
                    <span className="flex items-center gap-1.5"><Target className="h-3.5 w-3.5 text-secondary" /> {task.category}</span>
                  </div>
                </div>

                <div className="border-t border-white/5 p-4 flex gap-2 bg-black/20">
                  <Button className="flex-1 bg-primary hover:bg-primary/90 shadow-lg shadow-primary/20" onClick={() => { setFocusTask(task); toast.success(`Starting: ${task.title}`); }}>
                    <Play className="w-4 h-4 mr-2" /> Start Now
                  </Button>
                  <Button variant="outline" size="icon" className="border-white/10 hover:bg-white/10" onClick={() => toggleSave(task.id)}>
                    {savedTasks.includes(task.id) ? <CheckCircle2 className="w-4 h-4 text-success" /> : <Bookmark className="w-4 h-4" />}
                  </Button>
                </div>
              </motion.div>
            ))}
          </AnimatePresence>
        </div>
      )}
      {/* Focus Mode overlay — launched by Start Now */}
      <FocusMode isOpen={!!focusTask} onClose={() => setFocusTask(null)} taskTitle={focusTask?.title} />
    </DashboardLayout>
  );
}
